type: module
nickname: serverpod_json_rpc_2
client_package_path: ../serverpod_json_rpc_2_client

extraClasses:
  - package:serverpod_json_rpc_2_shared/serverpod_json_rpc_2_shared.dart:JsonRpc2Message
