name: serverpod_json_rpc_2_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  json_rpc_2: ^3.0.2
  serverpod_serialization: 1.2.5
  stream_channel: ^2.1.2

dev_dependencies:
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.7.0
