name: serverpod_json_rpc_2_client
description: Starting point for a Serverpod module client.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  serverpod_client: 1.2.5
  serverpod_json_rpc_2_shared: 1.0.0
