name: serverpod_json_rpc_2_server
description: Starting point for a Serverpod module.

environment:
  sdk: ^3.3.0

dependencies:
  json_rpc_2: ^3.0.2
  meta: ^1.11.0
  serverpod: 1.2.5
  serverpod_json_rpc_2_shared: 1.0.0
  stream_channel: ^2.1.2

dev_dependencies:
  custom_lint: ^0.6.4
  dart_pre_commit: ^5.3.0
  dart_test_tools: ^5.7.0

dart_pre_commit:
  flutter-compat: false
  pull-up-dependencies:
    allowed:
      - meta
