name: Publish serverpod_json_rpc_2_shared to pub.dev

on:
  push:
    tags:
      - "serverpod_json_rpc_2_shared-v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      tagPrefix: serverpod_json_rpc_2_shared-v
      workingDirectory: serverpod_json_rpc_2_shared
